INCLUDEPATH += $$PWD
SOURCES += \
    $$PWD/abstracteditorfactorybase.cpp \
    $$PWD/abstractpropertybrowser.cpp \
    $$PWD/abstractpropertymanager.cpp \
    $$PWD/booleditwidget.cpp \
    $$PWD/browseritem.cpp \
    $$PWD/buttonpropertybrowser.cpp \
    $$PWD/chareditwidget.cpp \
    $$PWD/coloreditwidget.cpp \
    $$PWD/cursordatabase.cpp \
    $$PWD/fonteditwidget.cpp \
    $$PWD/groupboxpropertybrowser.cpp \
    $$PWD/property.cpp \
    $$PWD/propertyeditordelegate.cpp \
    $$PWD/propertyeditorview.cpp \
    $$PWD/treepropertybrowser.cpp \
    $$PWD/variantproperty.cpp \
    $$PWD/private/abstractpropertybrowser_p.cpp \
    $$PWD/private/abstractpropertymanager_p.cpp \
    $$PWD/private/browseritem_p.cpp \
    $$PWD/private/buttonpropertybrowser_p.cpp \
    $$PWD/private/groupboxpropertybrowser_p.cpp \
    $$PWD/private/property_p.cpp \
    $$PWD/private/propertybrowserutils_p.cpp \
    $$PWD/private/treepropertybrowser_p.cpp \
    $$PWD/private/variantproperty_p.cpp \
    $$PWD/editorfactory/chareditorfactory.cpp \
    $$PWD/editorfactory/checkboxfactory.cpp \
    $$PWD/editorfactory/coloreditorfactory.cpp \
    $$PWD/editorfactory/cursoreditorfactory.cpp \
    $$PWD/editorfactory/dateeditfactory.cpp \
    $$PWD/editorfactory/datetimeeditfactory.cpp \
    $$PWD/editorfactory/doublespinboxfactory.cpp \
    $$PWD/editorfactory/enumeditorfactory.cpp \
    $$PWD/editorfactory/fonteditorfactory.cpp \
    $$PWD/editorfactory/keysequenceeditorfactory.cpp \
    $$PWD/editorfactory/lineeditfactory.cpp \
    $$PWD/editorfactory/scrollbarfactory.cpp \
    $$PWD/editorfactory/sliderfactory.cpp \
    $$PWD/editorfactory/spinboxfactory.cpp \
    $$PWD/editorfactory/timeeditfactory.cpp \
    $$PWD/editorfactory/varianteditorfactory.cpp \
    $$PWD/editorfactory/private/chareditorfactory_p.cpp \
    $$PWD/editorfactory/private/checkboxfactory_p.cpp \
    $$PWD/editorfactory/private/coloreditorfactory_p.cpp \
    $$PWD/editorfactory/private/cursoreditorfactory_p.cpp \
    $$PWD/editorfactory/private/dateeditfactory_p.cpp \
    $$PWD/editorfactory/private/datetimeeditfactory_p.cpp \
    $$PWD/editorfactory/private/doublespinboxfactory_p.cpp \
    $$PWD/editorfactory/private/editorfactory_p.cpp \
    $$PWD/editorfactory/private/enumeditorfactory_p.cpp \
    $$PWD/editorfactory/private/fonteditorfactory_p.cpp \
    $$PWD/editorfactory/private/keysequenceeditorfactory_p.cpp \
    $$PWD/editorfactory/private/lineeditfactory_p.cpp \
    $$PWD/editorfactory/private/scrollbarfactory_p.cpp \
    $$PWD/editorfactory/private/sliderfactory_p.cpp \
    $$PWD/editorfactory/private/spinboxfactory_p.cpp \
    $$PWD/editorfactory/private/timeeditfactory_p.cpp \
    $$PWD/propertymanager/boolpropertymanager.cpp \
    $$PWD/propertymanager/charpropertymanager.cpp \
    $$PWD/propertymanager/colorpropertymanager.cpp \
    $$PWD/propertymanager/cursorpropertymanager.cpp \
    $$PWD/propertymanager/datepropertymanager.cpp \
    $$PWD/propertymanager/datetimepropertymanager.cpp \
    $$PWD/propertymanager/doublepropertymanager.cpp \
    $$PWD/propertymanager/enumpropertymanager.cpp \
    $$PWD/propertymanager/flagpropertymanager.cpp \
    $$PWD/propertymanager/fontpropertymanager.cpp \
    $$PWD/propertymanager/grouppropertymanager.cpp \
    $$PWD/propertymanager/intpropertymanager.cpp \
    $$PWD/propertymanager/keysequencepropertymanager.cpp \
    $$PWD/propertymanager/localepropertymanager.cpp \
    $$PWD/propertymanager/metaenumprovider.cpp \
    $$PWD/propertymanager/metaenumwrapper.cpp \
    $$PWD/propertymanager/pointfpropertymanager.cpp \
    $$PWD/propertymanager/pointpropertymanager.cpp \
    $$PWD/propertymanager/rectfpropertymanager.cpp \
    $$PWD/propertymanager/rectpropertymanager.cpp \
    $$PWD/propertymanager/sizefpropertymanager.cpp \
    $$PWD/propertymanager/sizepolicypropertymanager.cpp \
    $$PWD/propertymanager/sizepropertymanager.cpp \
    $$PWD/propertymanager/stringpropertymanager.cpp \
    $$PWD/propertymanager/timepropertymanager.cpp \
    $$PWD/propertymanager/variantpropertymanager.cpp \
    $$PWD/propertymanager/private/boolpropertymanager_p.cpp \
    $$PWD/propertymanager/private/colorpropertymanager_p.cpp \
    $$PWD/propertymanager/private/datepropertymanager_p.cpp \
    $$PWD/propertymanager/private/datetimepropertymanager_p.cpp \
    $$PWD/propertymanager/private/doublepropertymanager_p.cpp \
    $$PWD/propertymanager/private/flagpropertymanager_p.cpp \
    $$PWD/propertymanager/private/fontpropertymanager_p.cpp \
    $$PWD/propertymanager/private/intpropertymanager_p.cpp \
    $$PWD/propertymanager/private/localepropertymanager_p.cpp \
    $$PWD/propertymanager/private/pointfpropertymanager_p.cpp \
    $$PWD/propertymanager/private/pointpropertymanager_p.cpp \
    $$PWD/propertymanager/private/rectfpropertymanager_p.cpp \
    $$PWD/propertymanager/private/rectpropertymanager_p.cpp \
    $$PWD/propertymanager/private/sizefpropertymanager_p.cpp \
    $$PWD/propertymanager/private/sizepolicypropertymanager_p.cpp \
    $$PWD/propertymanager/private/sizepropertymanager_p.cpp \
    $$PWD/propertymanager/private/stringpropertymanager_p.cpp \
    $$PWD/propertymanager/private/timepropertymanager_p.cpp \
    $$PWD/propertymanager/private/variantpropertymanager_p.cpp

HEADERS += \
    $$PWD/abstracteditorfactory.h \
    $$PWD/abstracteditorfactorybase.h \
    $$PWD/abstractpropertybrowser.h \
    $$PWD/abstractpropertymanager.h \
    $$PWD/booleditwidget.h \
    $$PWD/browseritem.h \
    $$PWD/buttonpropertybrowser.h \
    $$PWD/chareditwidget.h \
    $$PWD/coloreditwidget.h \
    $$PWD/cursordatabase.h \
    $$PWD/fonteditwidget.h \
    $$PWD/groupboxpropertybrowser.h \
    $$PWD/property.h \
    $$PWD/propertyeditordelegate.h \
    $$PWD/propertyeditorview.h \
    $$PWD/treepropertybrowser.h \
    $$PWD/variantproperty.h \
    $$PWD/private/abstractpropertybrowser_p.h \
    $$PWD/private/abstractpropertymanager_p.h \
    $$PWD/private/browseritem_p.h \
    $$PWD/private/buttonpropertybrowser_p.h \
    $$PWD/private/groupboxpropertybrowser_p.h \
    $$PWD/private/property_p.h \
    $$PWD/private/propertybrowserutils_p.h \
    $$PWD/private/treepropertybrowser_p.h \
    $$PWD/private/variantproperty_p.h \
    $$PWD/editorfactory/chareditorfactory.h \
    $$PWD/editorfactory/checkboxfactory.h \
    $$PWD/editorfactory/coloreditorfactory.h \
    $$PWD/editorfactory/cursoreditorfactory.h \
    $$PWD/editorfactory/dateeditfactory.h \
    $$PWD/editorfactory/datetimeeditfactory.h \
    $$PWD/editorfactory/doublespinboxfactory.h \
    $$PWD/editorfactory/enumeditorfactory.h \
    $$PWD/editorfactory/fonteditorfactory.h \
    $$PWD/editorfactory/keysequenceeditorfactory.h \
    $$PWD/editorfactory/lineeditfactory.h \
    $$PWD/editorfactory/scrollbarfactory.h \
    $$PWD/editorfactory/sliderfactory.h \
    $$PWD/editorfactory/spinboxfactory.h \
    $$PWD/editorfactory/timeeditfactory.h \
    $$PWD/editorfactory/varianteditorfactory.h \
    $$PWD/editorfactory/private/chareditorfactory_p.h \
    $$PWD/editorfactory/private/checkboxfactory_p.h \
    $$PWD/editorfactory/private/coloreditorfactory_p.h \
    $$PWD/editorfactory/private/cursoreditorfactory_p.h \
    $$PWD/editorfactory/private/dateeditfactory_p.h \
    $$PWD/editorfactory/private/datetimeeditfactory_p.h \
    $$PWD/editorfactory/private/doublespinboxfactory_p.h \
    $$PWD/editorfactory/private/editorfactory_p.h \
    $$PWD/editorfactory/private/enumeditorfactory_p.h \
    $$PWD/editorfactory/private/fonteditorfactory_p.h \
    $$PWD/editorfactory/private/keysequenceeditorfactory_p.h \
    $$PWD/editorfactory/private/lineeditfactory_p.h \
    $$PWD/editorfactory/private/scrollbarfactory_p.h \
    $$PWD/editorfactory/private/sliderfactory_p.h \
    $$PWD/editorfactory/private/spinboxfactory_p.h \
    $$PWD/editorfactory/private/timeeditfactory_p.h \
    $$PWD/editorfactory/private/varianteditorfactory_p.h \
    $$PWD/propertymanager/boolpropertymanager.h \
    $$PWD/propertymanager/charpropertymanager.h \
    $$PWD/propertymanager/colorpropertymanager.h \
    $$PWD/propertymanager/cursorpropertymanager.h \
    $$PWD/propertymanager/datepropertymanager.h \
    $$PWD/propertymanager/datetimepropertymanager.h \
    $$PWD/propertymanager/doublepropertymanager.h \
    $$PWD/propertymanager/enumpropertymanager.h \
    $$PWD/propertymanager/flagpropertymanager.h \
    $$PWD/propertymanager/fontpropertymanager.h \
    $$PWD/propertymanager/grouppropertymanager.h \
    $$PWD/propertymanager/intpropertymanager.h \
    $$PWD/propertymanager/keysequencepropertymanager.h \
    $$PWD/propertymanager/localepropertymanager.h \
    $$PWD/propertymanager/metaenumprovider.h \
    $$PWD/propertymanager/metaenumwrapper.h \
    $$PWD/propertymanager/pointfpropertymanager.h \
    $$PWD/propertymanager/pointpropertymanager.h \
    $$PWD/propertymanager/rectfpropertymanager.h \
    $$PWD/propertymanager/rectpropertymanager.h \
    $$PWD/propertymanager/sizefpropertymanager.h \
    $$PWD/propertymanager/sizepolicypropertymanager.h \
    $$PWD/propertymanager/sizepropertymanager.h \
    $$PWD/propertymanager/stringpropertymanager.h \
    $$PWD/propertymanager/timepropertymanager.h \
    $$PWD/propertymanager/variantpropertymanager.h \
    $$PWD/propertymanager/private/boolpropertymanager_p.h \
    $$PWD/propertymanager/private/charpropertymanager_p.h \
    $$PWD/propertymanager/private/colorpropertymanager_p.h \
    $$PWD/propertymanager/private/cursorpropertymanager_p.h \
    $$PWD/propertymanager/private/datepropertymanager_p.h \
    $$PWD/propertymanager/private/datetimepropertymanager_p.h \
    $$PWD/propertymanager/private/doublepropertymanager_p.h \
    $$PWD/propertymanager/private/enumpropertymanager_p.h \
    $$PWD/propertymanager/private/flagpropertymanager_p.h \
    $$PWD/propertymanager/private/fontpropertymanager_p.h \
    $$PWD/propertymanager/private/intpropertymanager_p.h \
    $$PWD/propertymanager/private/keysequencepropertymanager_p.h \
    $$PWD/propertymanager/private/localepropertymanager_p.h \
    $$PWD/propertymanager/private/pointfpropertymanager_p.h \
    $$PWD/propertymanager/private/pointpropertymanager_p.h \
    $$PWD/propertymanager/private/propertymanagerutils_p.h \
    $$PWD/propertymanager/private/rectfpropertymanager_p.h \
    $$PWD/propertymanager/private/rectpropertymanager_p.h \
    $$PWD/propertymanager/private/sizefpropertymanager_p.h \
    $$PWD/propertymanager/private/sizepolicypropertymanager_p.h \
    $$PWD/propertymanager/private/sizepropertymanager_p.h \
    $$PWD/propertymanager/private/stringpropertymanager_p.h \
    $$PWD/propertymanager/private/timepropertymanager_p.h \
    $$PWD/propertymanager/private/variantpropertymanager_p.h

RESOURCES += \
    $$PWD/propertybrowser.qrc
